include:
  - project: riafox/rfx/devops
    ref: node-18
    file: gitlab-ci-templates/rfx-init.yml
  - project: riafox/rfx/devops
    ref: node-18
    file: gitlab-ci-templates/rfx-build.yml
  - project: riafox/rfx/devops
    ref: node-18
    file: gitlab-ci-templates/rfx-dependencies.yml

variables:
  PROJECT: caballus

dependencies:
  extends: .dependencies_rfx
  only:
    refs:
      - uat
      - master

build:ion-horse-profile:
  extends: .build_rfx
  variables:
    SUBPROJECT: ion-horse-profile
  only:
    refs:
      - uat
      - master
    changes:
      - package.json
      - libs/common/**/*
      - libs/ui-common/**/*
      - libs/ui-library/**/*
      - apps/ion-horse-profile/**/*

build:ion-caballus:
  extends: .build_rfx
  variables:
    SUBPROJECT: ion-caballus
  only:
    refs:
      - uat
      - master
    changes:
      - package.json
      - libs/common/**/*
      - libs/ui-common/**/*
      - libs/ui-library/**/*
      - apps/ion-caballus/**/*

# NGX isn't used in Caballus
#
# build:ngx-caballus:
#   extends: .build_rfx
#   variables:
#   SUBPROJECT: ngx-caballus
#   only:
#   refs:
#     - uat
#     - master
#   changes:
#     - package.json
#     - libs/common/**/*
#     - libs/ui-common/**/*
#     - libs/ui-common/**/*
#     - apps/ngx-caballus/**/*

# build:ngx-caballus-qa:
#   extends: .build_rfx
#   variables:
#   PROJECT: caballus-qa
#   SUBPROJECT: ngx-caballus
#   only:
#   refs:
#     - qa
#   changes:
#     - package.json
#     - libs/common/**/*
#     - libs/ui-common/**/*
#     - libs/ui-common/**/*
#     - apps/ngx-caballus/**/*

build:nst-caballus:
  extends: .build_rfx
  variables:
    SUBPROJECT: nst-caballus
  only:
    refs:
      - uat
      - master
    changes:
      - package.json
      - libs/common/**/*
      - libs/api-common/**/*
      - apps/nst-caballus/**/*
